image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    test: "Example.Test"

before_script:
    - "cd WebApplication1"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    #script: 
        #- "cd $test"
        #- "dotnet test"