name: Docker Image CI-Staging

on:
  push:
    branches: [ "Staging" ]
  pull_request:
    branches: [ "Staging" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./WebApplication1/Dockerfile --tag my-image-name:$(date +%s)

    - name: Push Docker Image 
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER}}
        password: ${{ secrets.DOCKER_HUB_PASS}}
        dockerfile: ./WebApplication1/Dockerfile
        tags: latest